require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

inherit_gem:
  syntax_tree: config/rubocop.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1

Gemspec/RequireMFA:
  Enabled: false

Layout/LineLength:
  Max: 120

Lint/StructNewOverride:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes
