name: Approve and merge dependabot PRs

on: pull_request

permissions:
  pull-requests: write

jobs:
  approve:
    runs-on: ubuntu-latest
    env:
      PR_URL: ${{ github.event.pull_request.html_url }}
      GITHUB_TOKEN: ${{ secrets.AUTO_APPROVE_AND_MERGE_TOKEN }}

    steps:
      - name: Enable auto-merge
        run: gh pr merge --auto --squash "$PR_URL"
