name: Dependabot

on: pull_request

permissions:
  pull-requests: write

jobs:
  dependabot:
    name: Auto approve and merge
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'

    env:
      PR_URL: ${{ github.event.pull_request.html_url }}
      GITHUB_TOKEN: ${{ secrets.DEPENDABOT_TOKEN }}

    steps:
      - name: Enable auto-merge
        run: gh pr merge --auto --merge "$PR_URL"

      - name: Approve the PR
        run: gh pr review --approve "$PR_URL"
